### ISSUE TITLE
Update bunsen-images-extra for the helium release

### ISSUE THREAD

**Issue by hhhorb** [BunsenLabs/bunsen-images-extra#3]
Non-critical as far as the "for the release" part, but we should examine this since it is an install option in bl-welcome.

The package is currently ~116 MB and has a lot of repetition (different resolutions for the same wall) and several of the walls are branded as hydrogen. If chosen, this package slows down first-run A LOT, without a lot of benifit.

I'd like to cherry-pick the walls and other graphics for a bunsen-helium-images-extra package and remove bunsen-images-extra from bl-welcome in helium. Also maybe add an emphasis that the optional steps in bl-welcome can be run at a later time than at your first login so users can get running quickly if they wish without second guessing themselves.

**Comment by tknomanzr** [comment]
Yeah, 116 MB is nothing for me but I have seen reports of folks who are struggling. Should we separate the "extra" Helium images from the "extra" Hydrogen images maybe? I would like to see it all stay around for historical purposes but splitting it into two packages would certainly reduce the download size.

**Comment by hhhorb** [comment]
I've uploaded ututo's wallpapers (helium-ututo) to my repo and the whole folder, with plenty of redundancy, is 2.6 MB. images-extra is bloated IMO.

https://github.com/hhhorb/bunsen-wallpapers/tree/master/helium-ututo/beam-low-poly

**Comment by hhhorb** [comment]
>Should we separate the "extra" Helium images from the "extra" Hydrogen images maybe? I would like to see it all stay around for historical purposes but splitting it into two packages would certainly reduce the download size.

That's what I'm proposing, archiving bunsen-images-extra and moving forward with bunsen-*release*-images-extra that has only the best of our extra images for that release or upgrade. For example, include the largest resolutions of damos and ututos walls and keep the rest here on GitHub.

**Comment by tknomanzr** [comment]
Sounds good to me.

**Comment by tknomanzr** [comment]
Quite a few of those images are in our deviant art channel, I believe. [https://bunsenlabs.deviantart.com/gallery/55294289/Wallpapers](url)

**Comment by hhhorb** [comment]
^ Sorry, that link is a 404 for me. I'm sure that's a copy/pasta :D 

https://bunsenlabs.deviantart.com/gallery/55294289/Wallpapers

**Comment by tknomanzr** [comment]
Sorry. Did not build the link properly.

**Comment by hhhorb** [comment]
dev repo...

https://github.com/hhhorb/bunsen-wallpapers/tree/master/bunsen-helium-images-extra-dev

**Comment by johnraff** [comment]
> Non-critical as far as the "for the release" part, but we should examine this since it is an install option in bl-welcome.

I'm not clear here how much of this you are suggesting should be done for the Helium release. You say "non-critical" but go on to point out that it's a problem for new installers.

I do agree that **b-i-e** is too big - and a recent Youtube reviewer clicked to install it apparently thinking it was going to bring in a whole set of important software, not a bunch of mostly redundant image files! In fact that person went out of his way to say that it was very important to install everything that bl-welcome offered! That's totally wrong of course. After the first system checks, many users would just want to skip everything.

> Also maybe add an emphasis that the optional steps in bl-welcome can be run at a later time

Could you run bl-welcome in a Helium install, read the current messages and suggest which ones need changing, and in what way? 

> Quite a few of those images are in our deviant art channel, I believe.

...and some nice stuff there! We need to think a bit about what we should be packaging here and what we can leave on DA.

> dev repo...

Just what I was thinking: https://github.com/BunsenLabs/bunsen-images/issues/9#issuecomment-380644578 But I would advocate leaving out the "Helium" in the name perhaps. Different releases will have different versions of the package anyway, and we can put old stuff in eg **bunsen-images-archives** or something.

But anyway, can we discuss this whole image organization thing carefully, with involvement from other devs and forum members, *after* the Helium release?

Just to point out, now that we're using the official BL package repos, any package upgrades have to be done via @2ion who's quite busy, so let's keep the last-minute upgrades down to what's essential. (When we were on the experimental repo I could knock one out in a few minutes.) If **bunsen-welcome** *really* needs changing now, it can be done of course.

(And it is in fact possible to bundle pre-release versions of packages inside the iso.)

**Comment by hhhorb** [comment]
^ Agreed to all, John. It's a proposal, better sooner than later, I thought. Implement at your discretion.

**Comment by tknomanzr** [comment]
> I do agree that b-i-e is too big - and a recent Youtube reviewer clicked to install it apparently thinking it was going to bring in a whole set of important software, not a bunch of mostly redundant image files! In fact that person went out of his way to say that it was very important to install everything that bl-welcome offered! That's totally wrong of course. After the first system checks, many users would just want to skip everything.

To be fair @johnraff the guy wasn't precisely the sharpest pencil in the box. I did envy his sound system, however. I just took it as a view from someone who might be a complete newcomer. And yes, we can discuss after Helium releases. But I like your idea for the dev repository. There should be some guidelines we should discuss as well such as don't squash layers in originals, etc, so I do encourage a healthy discussion.

 I personally try to take the view that the things we create for this organization have the potential to exist past our time as devs here. As we have learned, things can happen and life can intrude, so I encourage us all to think about how to structure code, art, etc with that idea in mind.

**Comment by johnraff** [comment]
> I personally try to take the view that the things we create for this organization have the potential to exist past our time as devs here.

Becoming more and more aware of this these days. Let's do what we can to make it easy for new people to come in and take over.

**Comment by johnraff** [comment]
Bunsen-images-extra has been dropped for the moment, and we are shipping bunsen-images-archives with only default images from previous releases. Closing this issue - please open a new one if you want to discuss what other extra images we could offer in 2023.
