### ISSUE TITLE
Rename repo to bunsen-images-archives?

### ISSUE THREAD

**Issue by rbh-se** [BunsenLabs/bunsen-images-extra#4]
As the package the repo builds, now is bunsen-images-archives, should then not the repo also be renamed?

**Comment by johnraff** [comment]
There is no rule that a source repository should have the same name as a package that it builds. There are many cases of source code that builds multiple binary packages with different names, and often not one of the binary packages has the same name as the source code. ( First example I found: [libnotify](https://packages.debian.org/source/sid/libnotify) )

There is a possibility that in the future the "bunsen-images-extra" source code might build a binary package named "bunsen-images-extra", holding some of the miscellaneous images that are still in that repository.
